language: python

sudo: required
dist: trusty

virtualenv:
  system_site_packages: true

matrix:
  include:
    - python: "2.7"
      addons:
        apt:
          packages:
            - avahi-daemon
            - python-dbus
            - python-gobject-2
            - python-networkmanager
            - python-dev

script:
  - find .
  - python setup.py build test
